config/routes.rb
Rails.application.routes.draw do
  resources :orders, only: [:create]

  resources :events, only: [:index] do
    member do
      get :tickets
    end  
    post :activate
    post :deactivate
    collection do
      post :edit_cart
      post :edit_cart_cert
      get :cart
      post :promo
      post :get_remain
    end  
  end  
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  root 'api#index'
  get '/catalog/feed', to: 'api#retail_catalog'
  get '/pay_status', to: 'api#rpay_status'

end

app/models/event.rb
class Event < ActiveRecord::Base
  include ActionView::Helpers::NumberHelper

  has_many :order_items
  has_many :orders, through: :order_items
  has_many :clients, through: :orders
  has_and_belongs_to_many :admin_users
  belongs_to :category
  belongs_to :address
  has_many :promocodes
  has_many :cart_items
  
  audited
  resourcify
  
  before_save :create_admin_link
  
  has_attached_file :image,
                  styles: { admin: '255x100#', w200: '250', w360: '360' }
  validates_attachment_content_type :image,
                                    content_type: /\Aimage\/.*\Z/
                
  scope :all_for_user, ->(id) { joins("INNER JOIN admin_users_events ON admin_users_events.event_id = events.id AND admin_users_events.admin_user_id = #{id}")}
  scope :visible, ->{ where visible: true }
  scope :current, ->{ visible.where("start_date > ?", Time.now - 30.minutes).order("events.start_date ASC") }
  scope :current_for_user, ->(id) { current.where admin_user_id: id }
#  scope :for_admins, ->{ visible.where("start_date > ? AND start_date < ?", Time.now - 30.minutes, Time.now + 2.hours) }
  scope :for_admins, ->{ visible.where("(start_date > ?) AND (end_date > ?)", Time.now - 30.minutes, Time.now) }
  scope :filter_by_city, ->(city){ includes(:category).where(categories: {name: city == "SPB" ? "Санкт-Петербург" : "Москва"}).references(:category).order("events.start_date ASC") }
  
  
  validates :title, :start_date, :end_date, :image, :address_id, :max_guests, :category_id, presence: true
  
  def painter
    admin_users.includes(:roles).where(roles: { name: "Художник" }).references(:roles).first || AdminUser.new
  end
  
  def human_date
    if start_date < Date.tomorrow and start_date > Date.today
      'Сегодня'
    elsif (start_date + 1.day) < Date.tomorrow and start_date > Date.today
      'Завтра'
    elsif (start_date + 2.days) < Date.tomorrow and (start_date + 1.day) > Date.tomorrow
      'Послезавтра'
    elsif start_date.wday == 1
      "Понедельник"
    elsif start_date.wday == 2
      "Вторник"
    elsif start_date.wday == 3
      "Среда"
    elsif start_date.wday == 4
      "Четверг"
    elsif start_date.wday == 5
      "Пятница"
    elsif start_date.wday == 6
      "Суббота"
    elsif start_date.wday == 7
      "Воскресенье"
    end
  end
  
  def full_date
    date = I18n.l start_date, format: :long
    "#{human_date}, #{date}"
  end
   
  def short_date
    I18n.l start_date, format: :short
  end

  def email_date
    I18n.l start_date, format: '%-d %B %H:%M'
  end
  
  def current?
    visible == true && start_date > (Time.now - 30.minutes)
  end
  
  def in_cart? cart
    return false unless cart
    cart.cart_items.current.map { |c| c.event }.include?(self)
  end
  
  def cart_quant cart
    return 1 unless in_cart? cart
    cart.cart_items.current.find { |c| c.event == self }.quant
  end
  
  def cart_cost cart
    return price unless in_cart? cart
    cart.cart_items.current.find { |c| c.event == self }.discount_cost# { |sum, i| sum + i.discount_cost}
  end
  
  def cart_discount_perc cart
    return "0%" unless in_cart? cart
#    "#{cart.cart_items.current.find { |c| c.event == self }.percent_by_quant}%"
    "#{cart.percent_by_quant}%"
  end
  
  def remain
    q = order_items.includes(:order).where(orders: {status: 1}).references(:order).sum(:quant)
    max_guests - q.to_i
  end
  
  def promocode
    promocodes.current.where.not(start_date: nil).order("start_date desc").first || promocodes.current.first
  end
  
  def rebuild_admin_link
    self.update_attribute :admin_link, SecureRandom.uuid
  end
  
  def for_admin?
    visible && (start_date > Time.now - 30.minutes) && (end_date > Time.now)
  end
  
  def admin_link_url
    host = Rails.env.production? ? "http://painty.rogov.lclients.ru/" : "http://localhost:3001/"
    host + "events/#{admin_link}/tickets" if for_admin?
  end
  
  def masters_salary
    admin_users.map { |au| au.total_salary }.sum
  end
  
  def cost_price
    masters_salary / (order_items.payed.count > 0 ? order_items.payed.count : 1)
  end



  def price_format price
    number_to_currency(price,  separator: ",", delimiter: " ", precision: 0, unit: 'р. ', format: "%n %u")
  end
  
  private
  
  def create_admin_link
    self.discount = true
    self.admin_link = SecureRandom.uuid unless self.admin_link
  end
  
 
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  include ActionView::Helpers::NumberHelper
  
  skip_before_filter :verify_authenticity_token
#  before_action :is_xhr?
  protect_from_forgery only: [:tickets, :activate, :deactivate]
  before_action  :img_url, :set_access_control_headers, except: [:tickets, :activate, :deactivate]

  helper_method :price_format, :hum_quant
  
  def index
    @cert = CertType.displayed.filter_by_city(params[:city]).first
    @events = Event.current.filter_by_city(params[:city])
    if @events.any?
      @first_evt = @events.first   
      @events = @events[1..-1]
    end  
    if params[:p_cart].present?
      @cart = Cart.find_by_id(params[:p_cart])
      if @cart
        @cart.cart_items.find_all { |ci| !ci.valid? }.each { |ci| ci.delete } 
        @cart.reload
      end  
    end 
  end

  def promo
    promo = Promocode.current.find_by_name(params[:promo])
    @cart = Cart.find_by_id(params[:p_cart])
    @cart_items = @cart.cart_items.current
    if @cart
      @cart.promocode = promo
      @cart.save
      @cart.reload     
    end
#    render text: promo.inspect
    render 'cart.js'
  end

  
  def edit_cart
    cart = Cart.find_by_id(params[:p_cart]) || Cart.create
    event = Event.current.find_by_id(params[:event])
    if event
      exist = cart.cart_items.where(event_id: event.id)
      if exist.any?
        if params[:quant].to_i < 1
          exist.delete_all
        else  
          exist.first.update_attribute :quant, params[:quant].to_i
        end
      else  
        cart.cart_items << CartItem.create(event_id: params[:event], quant: params[:quant].to_i )
      end
    end  
    cart.cart_items.find_all { |ci| !ci.valid_event? }.each { |ci| ci.delete }
    cart.reload
    render json: {p_cart: cart.id, discount: cart.percent_by_quant.to_s + "%", evts: cart.cart_items.current.map { |ci| [ci.event.id, ci.event.cart_cost(cart)] }}
  end
  
  def edit_cart_cert
    cart = Cart.find_by_id(params[:p_cart]) || Cart.create
    cert = CertType.find_by_id(params[:cert])
    if cert
      exist = cart.certificate if cart.certificate && cart.certificate.cert_type == cert
      if exist
        if params[:quant].to_i < 1
          exist.delete
        else  
          exist.update_attribute :quant, params[:quant].to_i
        end
      else  
        cart.certificate.delete if cart.certificate
        cart.certificate = Certificate.create(
          cert_type_id: cert.id, quant: params[:quant].to_i
        )
        cart.save
      end
    end  
    cart.reload
    render json: {p_cart: cart.id, cost: cart.certificate ? cart.certificate.cost : 0, discount: cart.percent_by_quant.to_s + "%", evts: cart.cart_items.current.map { |ci| [ci.event.id, ci.event.cart_cost(cart)] }}
  end
    
  def get_remain
    event = Event.current.find_by_id(params[:event])
    render json: {remain: event.remain}
  end
  
  
  
  def cart
    @cart = Cart.find_by_id params[:cart]
    @cart_items = @cart.cart_items.current
  end
  
  def tickets
    @event = Event.for_admins.find_by_admin_link params[:id]
    unless @event
      render text: "Вечеринка не найдена!"
    else
      @tickets = @event.order_items.sort_by { |oi| oi.order.client.fie }
      @page_title = "Painty. Билеты на вечеринку: #{@event.title}" 
      render layuot: 'application'
    end  
  end
  
  def activate
    @order_item = OrderItem.find params[:ticket]
    @order_item.update_attribute :activated, @order_item.activated.to_i + 1 if @order_item.activated < @order_item.quant
    @order_item.reload
  end
  
  def deactivate
    @order_item = OrderItem.find params[:ticket]
    @order_item.update_attribute :activated, @order_item.activated.to_i - 1 if @order_item.activated > 0
    @order_item.reload
    render :activate
  end
  
    
  def price_format price
    number_to_currency(price,  separator: ",", delimiter: " ", precision: 0, unit: 'р. ', format: "%n %u")
  end
  
  def hum_quant(quant)
    pl =
      if (quant == 1)
        " место " 
      elsif quant > 1 && quant < 5 
        " места "
      elsif quant > 4
        " мест "
      end  
    quant.to_s + pl
  end
  
  
  
  def set_access_control_headers
#    headers['Access-Control-Allow-Origin'] = 'http://localhost:3001'
    response.headers["Content-Type"] = "text/javascript; charset=utf-8"
    headers['Access-Control-Allow-Origin'] = '*'
    headers['Access-Control-Allow-Methods'] = 'POST, GET, OPTIONS'
    headers['Access-Control-Allow-Headers'] = '*, x-requested-with'
  end
  
  
  private
    
    def img_url
      @img_url = Rails.env.production? ? "http://painty.rogov.lclients.ru" : 'http://localhost:3001'
    end
  
    def is_xhr?
      render text: "No" unless request.xhr?
    end

    def event_params
      params.require(:event).permit(:title, :descr, :start_date, :end_date, :image, :address, :admin_user_id, :max_guests, :visible)
    end
end

app/views/events/_cart.slim
.step-content
  - if @cart.certificate
    .ticket-for-party
      .row
        .col-xs-4.col-sm-4.col-md-4.col-lg-3
          = image_tag @img_url + @cart.certificate.cert_type.img.url(:w200)
        .col-xs-8.col-sm-8.col-md-8.col-lg-9 style=("padding-left: 0;") 
          .row
            .col-lg-6
              p
                b 
                  ' #{@cart.certificate.cert_type.name}
              p.secondary-info.hidden-lg = hum_quant(@cart.certificate.quant)
              p.secondary-info.hidden-lg = price_format(@cart.certificate.cost)
              /p.secondary-info.hidden-lg 
                | Вы экономите #{price_format()}
            .ticket-for-party__price-details.col-lg-6.visible-lg-inline
              b = price_format(@cart.certificate.cost)
              span.secondary-info.hidden-xs
                span.secondary-info__br-substitution #{price_format(@cart.certificate.cert_type.price)} x #{hum_quant(@cart.certificate.quant)}
                /span.secondary-info__br-substitution Вы экономите #{price_format(ci.discount_rub)}
  - @cart_items.each do |ci|
    .ticket-for-party
      .row
        .col-xs-4.col-sm-4.col-md-4.col-lg-3
          = image_tag @img_url + ci.event.image.url(:w200)
        .col-xs-8.col-sm-8.col-md-8.col-lg-9 style=("padding-left: 0;") 
          .row
            .col-lg-6
              p
                b 
                  ' #{ci.event.title}
                  ' , #{ci.event.short_date}
              p.secondary-info.hidden-lg = ci.hum_quant
              p.secondary-info.hidden-lg = price_format(ci.discount_cost)
              p.secondary-info.hidden-lg 
                | Вы экономите #{price_format(ci.discount_rub)}
            .ticket-for-party__price-details.col-lg-6.visible-lg-inline
              b = price_format(ci.discount_cost)
              span.secondary-info.hidden-xs
                span.secondary-info__br-substitution #{price_format(ci.event.price)} x #{ci.hum_quant}
                span.secondary-info__br-substitution Вы экономите #{price_format(ci.discount_rub)}

.total-price-discount
  .row.hidden-xs.hidden-sm
    .col-md-6
      span
        a.link--dashed.small-font.capslock-font.js-promocode href="#" 
          | ПРОМОКОД&nbsp;
          span.js-promocode-text = @cart.promocode.name if @cart.promocode
      .js-promocode-field.input-group style=("width: 250px; padding-top: 0.5em; display: none") 
        input.form-control.js-promocode-input.js-promocode-input-lg placeholder="" type="text" /
        span.input-group-btn
          button.btn.btn-default.js-set-promocode type="button"  Применить
    .total-price.text-align-right.col-md-6
      p
        b Итого #{hum_quant(@cart.total_quant)}: #{price_format @cart.total_cost}
      p.secondary-info Вы экономите: #{price_format(@cart.total_discount_rub)}
  .row.hidden-md.hidden-lg
    .total-price.col-md-6
      p
        b Итого #{hum_quant(@cart.total_quant)}: #{price_format @cart.total_cost}
      p.secondary-info Вы экономите: #{price_format(@cart.total_discount_rub)}
    .col-xs-12
      span
        a.link--dashed.small-font.capslock-font.js-promocode href="#" 
          | 333 ПРОМОКОД&nbsp;
          span.js-promocode-text = @cart.promocode.name if @cart.promocode
      .js-promocode-field.input-group style=("width: 250px; padding-top: 0.5em; display: none") 
        input.form-control.js-promocode-input.js-promocode-input-sm placeholder="" type="text" /
        span.input-group-btn
          button.btn.btn-default.js-set-promocode type="button"  Использовать

.steps-wrapper__button-wrapper
  a href="#contacts" aria-controls="contacts" role="tab" data-toggle="tab" class="btn btn-painty--primary" Всё верно, далее →

app/views/events/_cert_info.slim
.row.no-padding.cert(class="#{'hidden' if !@cart || !@cart.certificate }")
  .col-xs-12.no-padding
    label.tickets-counter
      a.tickets-counter__dec –
      span.tickets-counter__val = hum_quant(@cart && @cart.certificate && @cart.certificate.quant.to_i > 0 ? @cart.certificate.quant : 1)
      a.tickets-counter__inc +
  .col-xs-12.no-padding
    .helper.helper--cart-status 
      ' Вы выбрали 
      span.quant  
        = hum_quant(@cart && @cart.certificate && @cart.certificate.quant.to_i > 0 ? @cart.certificate.quant : 1)
      ' на сумму 
      span.price 
        = price_format(@cart && @cart.certificate ? @cart.certificate.cost : 0)
      /' со скидкой 
      /span.discount 
      /= event.cart_discount_perc(cart)
      ' . Выберите ещё места на других вечеринках или 
      a.js-open-cart href="#"
        | перейдите к оформлению →

app/views/events/_contacts.slim
.step-header
  div
    b Представьтесь 
  .text-gray Шаг 2 из 4
form#contacts_form
  .step-content
    .contacts-wrapper
      .form-group
        label.col-sm-2.control-label for="input_name"  Имя
        .col-sm-5
          input#input_name.form-control placeholder="" type="text" required="required"
      .form-group
        label.col-sm-2.control-label for="input_last_name"  Фамилия
        .col-sm-5
          input#input_last_name.form-control placeholder="" type="text" required="required"
        span#helpBlock.col-sm-5.help-block
          span Спросим на входе
      .form-group
        label.col-sm-2.control-label for="input_phone"  Телефон
        .col-sm-5
          input#input_phone.form-control placeholder="+7-" type="phone" required="required"
        span#helpBlock.col-sm-5.help-block
          span Отправим код подтверждения
      .form-group
        label.col-sm-2.control-label for="input_email"  Эл. почта
        .col-sm-5
          input#input_email.form-control placeholder="" type="email" required="required"
        span#helpBlock.col-sm-5.help-block
          span Отправим информацию о брони
  .clearfix
  .steps-wrapper__button-wrapper
    a.link--dashed.js-open-tickets-tab aria-controls="tickets" data-toggle="tab" href="#tickets" role="tab" ← Назад
    | &nbsp;&nbsp;&nbsp;
    button.btn.btn-painty--primary id="to_payment" type="submit"  Перейти к оплате →
    button.btn.btn-painty--primary.hidden aria-controls="payment" data-toggle="tab" href="#payment" role="tab" id="to_payment2" type="submit"  Перейти к оплате →

app/views/events/_features.slim
.col-md-offset-1.col-md-3.hidden-xs.hidden-sm
  .no-padding
    .feature
      .feature__cover
        img src="http://images.tildacdn.info/233a9ea7-0e23-40c9-87b5-81d79c2ba6ae/grouptickets.png" /
      .feature__info
        | Забронируйте места сразу на всех друзей и получите скидку: от 3 участников &mdash; скидка 10%, а от 5 участников &mdash; 15%
    #cert-block.feature(data-cert-id="#{@cert.id}")
      .feature__cover
        = image_tag @img_url + @cert.img.url(:w200)
      .feature__info
        | Подарочный сертификат на посещение любой вечеринки
      == render partial: 'cert_info', locals: {cert: @cert, cart: @cart}  
      .feature__button-wrapper.participate(class="#{'hidden' if @cart && @cart.certificate}")
        a.btn.btn-painty--primary.btn-painty--big.js-add-cert href="#"  Подарить

app/views/events/_index.html.slim
= csrf_meta_tags

.row
  .party-wrapper.party-wrapper--key.col-xs-12.hidden-xs.hidden-sm(data-event-id="#{@first_evt.id}" data-event-price="#{@first_evt.price}" data-event-discount="#{@first_evt.discount}")
    table.party-borderless-table
      tr
        th
          table.party-borderless-table
            tr
              th.left-shadow.left-shadow--key
                img src="https://ucarecdn.com/a24e4d1d-b23a-43b3-b080-ddb12fed3660/pixel.png"
              th.cover.cover--key
                = image_tag @img_url + @first_evt.image.url(:w200)
              th.right-shadow.right-shadow--key
                img src="https://ucarecdn.com/a24e4d1d-b23a-43b3-b080-ddb12fed3660/pixel.png"
        th style='width: 100%; padding-left: 14px;'
          .sticker = @first_evt.full_date
          .title.title--key
            span.title__title-first 
              ' #{@first_evt.title}
            span.title__title-second 
              ' #{@first_evt.address.additional_name if @first_evt.address}

          .rest-map-links-wrapper
            span.restaurant
              = link_to 'Сайт ресторана', @first_evt.address.url, class: "link--gray", target: "_blank"
            span.map
              = link_to 'Показать на карте', @first_evt.address.maps, class: "link--gray", target: "_blank"

          == render partial: 'tickets_info', locals: {event: @first_evt, cart: @cart}

          .button-helper-wrapper.participate(class="#{'hidden' if @first_evt.in_cart?(@cart)}")
            a href="#" class="btn btn-painty--primary btn-painty--big js-add-tickets"
              | Участвовать
            span.helper.hidden-md
              | Ведёт #{@first_evt.painter.name}
              = image_tag @img_url + @first_evt.painter.img.url(:w32)
            span.helper.hidden-lg
              | Ведёт #{@first_evt.painter.name}
              = image_tag @img_url + @first_evt.painter.img.url(:w32)
            span.helper.helper--warning.hidden 
              | Осталось #{@first_evt.remain} мест


  .party-wrapper.party-wrapper--mobile.col-xs-12.hidden-md.hidden-lg(data-event-id="#{@first_evt.id}" data-event-price="#{@first_evt.price}" data-event-discount="#{@first_evt.discount}")
    .col-xs-12.no-padding
      table.party-borderless-table.party-borderless-table--mobile
        tr
          th.left-shadow
            img src="https://ucarecdn.com/a24e4d1d-b23a-43b3-b080-ddb12fed3660/pixel.png"
          th.cover.cover--mobile
            = image_tag @img_url + @first_evt.image.url(:w200)
          th.right-shadow
            img src="https://ucarecdn.com/a24e4d1d-b23a-43b3-b080-ddb12fed3660/pixel.png"

      .col-xs-12.party-info-wrapper
        .sticker.sticker--mobile = @first_evt.full_date
        .title
          span.title__title-first 
              ' #{@first_evt.title}
          span.title__title-second 
            ' #{@first_evt.address.additional_name if @first_evt.address}
        .rest-map-links-wrapper
          span.restaurant
            = link_to 'Сайт ресторана', @first_evt.address.url, class: "link--gray", target: "_blank"
          span.map
            = link_to 'Показать на карте', @first_evt.address.maps, class: "link--gray", target: "_blank"

        == render partial: 'tickets_info', locals: {event: @first_evt, cart: @cart}

        .participate(class="#{'hidden' if @first_evt.in_cart?(@cart)}")
          a href="#" class="btn btn-painty--primary btn-painty--big js-add-tickets"
            | Участвовать
          span.helper.helper--mobile
            | Ведёт #{@first_evt.painter.name}
            = image_tag @img_url + @first_evt.painter.img.url(:w32)



.row
  .col-md-8
    .row  
      - @events.each do |event|
        .party-wrapper.col-xs-12.hidden-xs.hidden-sm(data-event-id="#{event.id}" data-event-price="#{event.price}" data-event-discount="#{event.discount}")
          table.party-borderless-table
            tr
              th
                table.party-borderless-table
                  tr
                    th.left-shadow
                      img src="https://ucarecdn.com/a24e4d1d-b23a-43b3-b080-ddb12fed3660/pixel.png"
                    th.cover
                      = image_tag @img_url + event.image.url(:w200)
                    th.right-shadow
                      img src="https://ucarecdn.com/a24e4d1d-b23a-43b3-b080-ddb12fed3660/pixel.png"


              th
                .sticker = event.full_date
                .title
                  span.title__title-first 
                    ' #{event.title}
                  span.title__title-second 
                    ' #{event.address.additional_name if event.address}

                .rest-map-links-wrapper
                  span.restaurant
                    = link_to 'Сайт ресторана', event.address.url, class: "link--gray", target: "_blank"
                  span.map
                    = link_to 'Показать на карте', event.address.maps, class: "link--gray", target: "_blank"

                == render partial: 'tickets_info', locals: {event: event, cart: @cart}

                .button-helper-wrapper.participate(class="#{'hidden' if event.in_cart?(@cart)}")
                  a href="#" class="btn btn-painty--primary btn-painty--big js-add-tickets"
                    | Участвовать
                  span.helper.hidden-md
                    | Ведёт #{event.painter.name}
                    = image_tag @img_url + event.painter.img.url(:w32)
                  span.helper.hidden-lg
                    | Ведёт #{event.painter.name}
                    = image_tag @img_url + event.painter.img.url(:w32)
                  .helper.helper--warning
                    - if event.remain <= 10
                      | Осталось #{event.remain} мест




        .party-wrapper.party-wrapper--mobile.col-xs-12.hidden-md.hidden-lg(data-event-id="#{event.id}" data-event-price="#{event.price}" data-event-discount="#{event.discount}")
          .col-xs-12.no-padding
            table.party-borderless-table.party-borderless-table--mobile
              tr
                th.left-shadow
                  img src="https://ucarecdn.com/a24e4d1d-b23a-43b3-b080-ddb12fed3660/pixel.png"
                th.cover.cover--mobile
                  = image_tag @img_url + event.image.url(:w200)
                th.right-shadow
                  img src="https://ucarecdn.com/a24e4d1d-b23a-43b3-b080-ddb12fed3660/pixel.png"

            .col-xs-12.party-info-wrapper
              .sticker.sticker--mobile = event.full_date
              .title
                span.title__title-first 
                    ' #{event.title}
                span.title__title-second 
                  ' #{event.address.additional_name if event.address}
              .rest-map-links-wrapper
                span.restaurant
                  = link_to 'Сайт ресторана', event.address.url, class: "link--gray", target: "_blank"
                span.map
                  = link_to 'Показать на карте', event.address.maps, class: "link--gray", target: "_blank"

              == render partial: 'tickets_info', locals: {event: event, cart: @cart}

              .participate(class="#{'hidden' if event.in_cart?(@cart)}")
                a href="#" class="btn btn-painty--primary btn-painty--big js-add-tickets"
                  | Участвовать
                span.helper.helper--mobile 
                  | Ведёт #{event.painter.name}
                  = image_tag @img_url + event.painter.img.url(:w32)

  == render 'features' if @cert

app/views/events/_show.html.slim
.close ×
.img_block
  = image_tag @event.image.url(:w200), class: "ivt_prw"
.order_block
  h1 = @event.title
  p.purplecol = @event.address.address if @event.address
  p.orangecol 
    = @event.start_date
    '  -
    = @event.end_date.strftime("%H:%M")

  p.blackcol.ivt_descr = @event.descr
 
  hr
  == render 'orders/form'

  = form_tag "", id: "promocode" do
    = text_field_tag :promo, "", placeholder: "Промокод"
    = hidden_field_tag :event_id, @event.id
    = submit_tag "Применить", class: "button_promo"

app/views/events/_tickets_info.slim
.row.no-padding.tickets(class="#{'hidden' unless event.in_cart?(cart)}")
  .col-xs-12.no-padding
    label.tickets-counter
      a.tickets-counter__dec –
      span.tickets-counter__val = hum_quant(event.cart_quant(cart))
      a.tickets-counter__inc +
  .col-xs-12.no-padding
    .helper.helper--cart-status 
      ' Вы выбрали 
      span.quant  = hum_quant(event.cart_quant(cart))
      ' на сумму 
      span.price = price_format(event.cart_cost(cart))
      ' со скидкой 
      span.discount = event.cart_discount_perc(cart)
      ' . Выберите ещё места на других вечеринках или 
      a.js-open-cart href="#"
        | перейдите к оформлению →

app/views/events/_tr.html.haml
%td= @order_item.order.client.fie
%td
  = @order_item.quant
  &#47;
  = @order_item.activated
%td.col.col-actions
  = form_tag url_for(event_activate_path(@order_item.event)), class: "ticket_form", remote: true do 
    = hidden_field_tag :ticket, @order_item.id
    = submit_tag "+1", class: "activate" unless @order_item.used?
  = form_tag url_for(event_deactivate_path(@order_item.event)), class: "ticket_form", remote: true do 
    = hidden_field_tag :ticket, @order_item.id
    = submit_tag "- 1", class: "deactivate"

app/views/events/activate.js.slim
| $("#tr_#{@order_item.id}").html("#{j render 'tr'}");
| $("#tr_#{@order_item.id}").removeClass('used');
- if @order_item.used?
  | $("#tr_#{@order_item.id}").addClass('used');

| if ($("#hide_used").is(":not(:checked)"))
|   {$(".used").show('slow') }
| else 
|   { $(".used").hide('slow') }

app/views/events/cart.js.slim
- if !@cart_items.blank? || @cart.certificate
  | $("#cart").html("#{j render 'cart' }");
- else
  | $("#cart").text("КОРЗИНА ПУСТА");
  

app/views/events/index.js.slim
- if !@events.blank? || @first_evt
  | $("#shop").html("#{j render 'index' }");
- else
  | $("#shop").text("ВСЕ ВЕЧЕРИНКИ ПРОШЛИ");

  

app/views/events/show.js.slim
| $("#show_event").html("");
| $("#black_fog").show();
| $("#show_event").html("#{j render 'show' }");
| $("#show_event").show();

app/views/events/tickets.html.haml
#title_bar
  #titlebar_left
    %h2#page_title= @event.title

#active_admin_content
  %p 
    %b Спрятать использованные билеты
    = check_box_tag :hide_used
  %table(class="index_table index")
    %tr
      %th Клиент
      %th Всего билетов / использовано
      %th
    - @tickets.each do |t|
      %tr(class="#{'used' if t.used?}" id="tr_#{t.id}")
        %td= t.order.client.fie
        %td
          = t.quant
          &#47;
          = t.activated
        %td.col.col-actions
          = form_tag url_for(event_activate_path(@event)), class: "ticket_form", remote: true do 
            = hidden_field_tag :ticket, t.id
            = submit_tag "+1", class: "activate" unless t.used?
          = form_tag url_for(event_deactivate_path(@event)), class: "ticket_form", remote: true do 
            = hidden_field_tag :ticket, t.id
            = submit_tag "- 1", class: "deactivate"